on:
  release:
    types: [released]

jobs:
  torrent_deluge:
    runs-on: ubuntu-latest
    name: Add torrent to Deluge
    steps:
      - name: Create File
        run: echo "Hello, World!" > file.txt
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
            file: file.txt
